# Generated by Django 2.1.2 on 2018-11-16 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('nickname', models.CharField(default='', max_length=100)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach_id', models.CharField(max_length=255)),
                ('coach_name', models.CharField(default='', max_length=255)),
                ('coach_birthday', models.DateField(default='')),
                ('coach_intro', models.CharField(default='', max_length=600)),
                ('coach_signature', models.CharField(default='', max_length=100)),
                ('coach_title', models.CharField(default='', max_length=255)),
                ('student_num', models.CharField(default='0', max_length=255)),
                ('coach_head_img', models.CharField(default='', max_length=255)),
                ('coach_extra_img', models.CharField(default='', max_length=255)),
                ('coach_have_course', models.CharField(default='', max_length=255)),
                ('coach_course_type', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('course_intro', models.CharField(default='', max_length=600)),
                ('course_training_part', models.CharField(default='', max_length=100)),
                ('course_head_img', models.CharField(default='', max_length=255)),
                ('course_extra_img', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
